### ISSUE TITLE
java.lang.IllegalArgumentException对象copy问题

### ISSUE THREAD

**Issue by zhangweiguo702141367** [alibaba/tamper#12]
java.lang.IllegalArgumentException: Cannot find method public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
        at net.sf.cglib.reflect.FastMethod.helper(FastMethod.java:39) ~[cglib-3.2.4.jar:na]
        at net.sf.cglib.reflect.FastMethod.<init>(FastMethod.java:28) ~[cglib-3.2.4.jar:na]
        at net.sf.cglib.reflect.FastClass.getMethod(FastClass.java:104) ~[cglib-3.2.4.jar:na]
        at com.agapple.mapping.core.introspect.Introspector.getFastClass(Introspector.java:150) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.introspect.Introspector.getFastMethod(Introspector.java:65) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.introspect.PropertySetExecutor.discover(PropertySetExecutor.java:63) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.introspect.PropertyBatchExecutor.buildGetBulkBean(PropertyBatchExecutor.java:49) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.introspect.PropertyBatchExecutor.<init>(PropertyBatchExecutor.java:19) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.introspect.Uberspector.getBatchExecutor(Uberspector.java:47) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.BeanMappingExecutor.getSetBatchExecutor(BeanMappingExecutor.java:122) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.core.BeanMappingExecutor.execute(BeanMappingExecutor.java:51) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.BeanCopy.copy(BeanCopy.java:59) ~[mapping-1.0.0.jar:na]
        at com.agapple.mapping.BeanMappingUtil.copy(BeanMappingUtil.java:33) ~[mapping-1.0.0.jar:na]

**Comment by ponyWISE** [comment]
同问，遇到了一样的问题。请问这个项目还在维护么？
java.lang.IllegalArgumentException: Cannot find method public final void java.lang.Object.wait() throws java.lang.InterruptedException

	at net.sf.cglib.reflect.FastMethod.helper(FastMethod.java:39)
	at net.sf.cglib.reflect.FastMethod.<init>(FastMethod.java:28)
	at net.sf.cglib.reflect.FastClass.getMethod(FastClass.java:104)
	at com.alibaba.tamper.core.introspect.Introspector.getFastClass(Introspector.java:171)
	at com.alibaba.tamper.core.introspect.Introspector.getFastMethod(Introspector.java:66)
	at com.alibaba.tamper.core.introspect.FastPropertySetExecutor.discover(FastPropertySetExecutor.java:63)
	at com.alibaba.tamper.core.introspect.PropertyBatchExecutor.buildGetBulkBean(PropertyBatchExecutor.java:49)
	at com.alibaba.tamper.core.introspect.PropertyBatchExecutor.<init>(PropertyBatchExecutor.java:19)
	at com.alibaba.tamper.core.introspect.UberspectImpl.getBatchExecutor(UberspectImpl.java:36)
	at com.alibaba.tamper.core.BeanMappingExecutor.getGetBatchExecutor(BeanMappingExecutor.java:180)
	at com.alibaba.tamper.core.BeanMappingExecutor.execute(BeanMappingExecutor.java:52)
	at com.alibaba.tamper.BeanCopy.copy(BeanCopy.java:55)
	at com.haha.SimpleTest.TestBeanUtils(SimpleTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by agapple** [comment]
我关注一下，提供一下你们的cglib版本, beanmapping测试的代码
