### ISSUE TITLE
与 springboot 集成时报错

### ISSUE THREAD

**Issue by zengyufei** [alibaba/tamper#9]
java.lang.VerifyError: class net.sf.cglib.core.DebuggingClassWriter overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.sf.cglib.core.AbstractClassGenerator.<init>(AbstractClassGenerator.java:38)
	at net.sf.cglib.reflect.FastClass$Generator.<init>(FastClass.java:55)
	at net.sf.cglib.reflect.FastClass.create(FastClass.java:43)
	at net.sf.cglib.reflect.FastClass.create(FastClass.java:39)
	at com.alibaba.tamper.core.introspect.Introspector.getFastClass(Introspector.java:165)
	at com.alibaba.tamper.core.introspect.Introspector.getFastMethod(Introspector.java:66)
	at com.alibaba.tamper.core.introspect.FastPropertySetExecutor.discover(FastPropertySetExecutor.java:63)
	at com.alibaba.tamper.core.introspect.PropertyBatchExecutor.buildGetBulkBean(PropertyBatchExecutor.java:49)
	at com.alibaba.tamper.core.introspect.PropertyBatchExecutor.<init>(PropertyBatchExecutor.java:19)
	at com.alibaba.tamper.core.introspect.UberspectImpl.getBatchExecutor(UberspectImpl.java:36)
	at com.alibaba.tamper.core.BeanMappingExecutor.getGetBatchExecutor(BeanMappingExecutor.java:180)
	at com.alibaba.tamper.core.BeanMappingExecutor.execute(BeanMappingExecutor.java:52)
	at com.alibaba.tamper.BeanCopy.copy(BeanCopy.java:55)
	at com.zyf.springboot.BeanCopyTest.testCopy_ok(BeanCopyTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by agapple** [comment]
overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V

定义了一个final method ?
